# Generated by Django 4.1.1 on 2022-10-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_s3_path',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
    ]
